#========== JPA ?? ==========#
#?? ??? DB ???
spring.jpa.hibernate.ddl-auto=create
#SQL ?? (SystemOut ???? ???)
#spring.jpa.properties.hibernate.show_sql=true
#SQL ???
spring.jpa.properties.hibernate.format_sql=true
#SQL ?? ??
spring.jpa.properties.hibernate.use_sql_comments=true


#========== Logging ?? ==========#
#SQL ???? ? ??
logging.level.org.hibernate.type.descriptor.sql=trace
#SQL ??
logging.level.org.hibernate.sql=debug
#Log ?? ??
logging.level.root=info

#========== properties ?? ==========#
spring.profiles.include=datasource